name: test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install tools
      run: |
        sudo apt-get update
        sudo apt-get install -y make verilator libreadline-dev python3-kconfiglib

    - name: Install mill
      run: |
        curl -L https://repo1.maven.org/maven2/com/lihaoyi/mill-dist/1.1.5/mill-dist-1.1.5-mill.sh -o mill
        chmod +x mill
        sudo ln -sf $(pwd)/mill /usr/bin/mill

    - name: Run make check format
      run: make check

    - name: Run make test
      run: make test

    - name: Build simulator
      run: make verilator
